"""Historical forward-only replay engine for Fil Before Pump.

Replays qualified wallet entries from gmgn_wallet_history.json without using
future information at decision time. It measures forward MFE/MAE and target
hits at 6/12/24h. This is an observational backtest layer, not exchange
execution and not a claim of realized trading PnL.

It also measures a forward-only wallet-history cohort split. The engine scores
``pre_pump_first_entry_rate`` in its signal-wallet profiles, so this module
checks that assumption against realised forward outcomes. The split is decided
per entry using only rows strictly earlier than the entry timestamp, so it is
non-circular and leaks no future information. A symbol-level cohort split was
deliberately rejected: the replay population is generated by the same wallets
that build the profiles, so 94% of observations fall in the "has a profile"
cohort and the split carries almost no information.
"""
from __future__ import annotations
import json
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

HISTORY = Path("gmgn_wallet_history.json")
OUT = Path("historical_replay.json")
THRESHOLD_USD = 5000.0
WINDOWS = (6, 12, 24)
TARGETS = (5, 10, 20, 30)
FIRST_ENTRY = "FIRST_ENTRY"
REPEAT_ENTRY = "REPEAT_ENTRY"
COHORTS = (FIRST_ENTRY, REPEAT_ENTRY)


def num(v: Any, default: float = 0.0) -> float:
    try:
        return float(v)
    except (TypeError, ValueError):
        return default


def ts(row: dict[str, Any]) -> int:
    try:
        value = int(float(row.get("timestamp") or row.get("time") or row.get("ts") or 0))
    except (TypeError, ValueError):
        return 0
    return value // 1000 if value > 10**12 else value


def price(row: dict[str, Any]) -> float:
    return num(row.get("price_usd") or row.get("price") or row.get("priceUsd"))


def usd(row: dict[str, Any]) -> float:
    return num(row.get("amount_usd") or row.get("usd") or row.get("value_usd") or row.get("valueUsd") or row.get("quote_usd"))


def side(row: dict[str, Any]) -> str:
    return str(row.get("side") or row.get("type") or "").strip().lower()


def load() -> dict[str, list[dict[str, Any]]]:
    if not HISTORY.exists():
        return {}
    try:
        raw = json.loads(HISTORY.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return {str(w): v for w, v in raw.items() if isinstance(v, list)} if isinstance(raw, dict) else {}


def prior_qualified_buys(rows: list[dict[str, Any]], symbol: str, t0: int) -> int:
    """Count this wallet's qualified buys of the same symbol strictly before t0.

    Forward-only: rows at or after t0 are never inspected, so the resulting
    cohort label cannot contain information about the outcome being measured.
    """
    return sum(
        1 for r in rows
        if side(r) == "buy" and usd(r) >= THRESHOLD_USD
        and str(r.get("symbol") or "").upper() == symbol
        and 0 < ts(r) < t0
    )


def _window_stats(rows: list[dict[str, Any]], hours: int) -> dict[str, Any]:
    usable = [r for r in rows if str(hours) in r["windows"]]
    if not usable:
        return {
            "observations": 0, "hit_rate_pct": {str(t): None for t in TARGETS},
            "avg_mfe_pct": None, "avg_mae_pct": None,
        }
    return {
        "observations": len(usable),
        "hit_rate_pct": {
            str(t): round(
                sum(r["windows"][str(hours)]["targets_hit"][str(t)] for r in usable)
                / len(usable) * 100, 2,
            )
            for t in TARGETS
        },
        "avg_mfe_pct": round(sum(r["windows"][str(hours)]["mfe_pct"] for r in usable) / len(usable), 3),
        "avg_mae_pct": round(sum(r["windows"][str(hours)]["mae_pct"] for r in usable) / len(usable), 3),
    }


def replay(data: dict[str, list[dict[str, Any]]] | None = None, out_path: Path | None = OUT) -> dict[str, Any]:
    """Replay qualified entries. ``out_path`` exists so tests can write to a
    temporary file instead of overwriting the committed dataset artifact."""
    data = data if data is not None else load()
    observations: list[dict[str, Any]] = []
    by_wallet = defaultdict(list)

    for wallet, rows in data.items():
        clean = [r for r in rows if isinstance(r, dict) and ts(r) > 0]
        by_symbol = defaultdict(list)
        for row in clean:
            symbol = str(row.get("symbol") or "").upper()
            if symbol and price(row) > 0:
                by_symbol[symbol].append(row)
        for symbol in by_symbol:
            by_symbol[symbol].sort(key=ts)

        buys = [r for r in clean if side(r) == "buy" and usd(r) >= THRESHOLD_USD and price(r) > 0]
        for buy in sorted(buys, key=ts):
            symbol = str(buy.get("symbol") or "").upper()
            t0, entry = ts(buy), price(buy)
            if not symbol or not t0 or entry <= 0:
                continue
            prior = prior_qualified_buys(clean, symbol, t0)
            future = [r for r in by_symbol[symbol] if ts(r) > t0 and ts(r) - t0 <= 24 * 3600 and price(r) > 0]
            if not future:
                continue
            row = {
                "wallet": wallet,
                "symbol": symbol,
                "entry_timestamp": t0,
                "entry_price": entry,
                "entry_usd": usd(buy),
                "prior_qualified_buys": prior,
                "entry_type": FIRST_ENTRY if prior == 0 else REPEAT_ENTRY,
                "windows": {},
            }
            for hours in WINDOWS:
                prices = [price(r) for r in future if ts(r) - t0 <= hours * 3600]
                if not prices:
                    continue
                mfe = max(prices) / entry - 1
                mae = min(prices) / entry - 1
                row["windows"][str(hours)] = {
                    "mfe_pct": round(mfe * 100, 3),
                    "mae_pct": round(mae * 100, 3),
                    "targets_hit": {str(t): mfe * 100 >= t for t in TARGETS},
                }
            observations.append(row)
            by_wallet[wallet].append(row)

    stats = {str(hours): _window_stats(observations, hours) for hours in WINDOWS}

    # Forward-only wallet-history cohort split, aggregated over every
    # observation before the stored tail is truncated.
    cohort_stats = {
        cohort: {str(hours): _window_stats([o for o in observations if o["entry_type"] == cohort], hours) for hours in WINDOWS}
        for cohort in COHORTS
    }

    result = {
        "mode": "HISTORICAL_FORWARD_ONLY",
        "orders_enabled": False,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "threshold_usd": THRESHOLD_USD,
        "observation_count": len(observations),
        "wallet_count": len(by_wallet),
        "statistics": stats,
        "cohort_statistics": cohort_stats,
        "cohort_definition": {
            FIRST_ENTRY: "wallet had no prior qualified buy of this symbol before the entry",
            REPEAT_ENTRY: "wallet had at least one prior qualified buy of this symbol before the entry",
        },
        "observations": observations[-5000:],
        "methodology": {
            "entry": "provider-labelled GMGN buy >= $5K with valid entry price",
            "future_data": "only timestamps after entry, maximum 24h",
            "metrics": "forward MFE/MAE and target-hit rates",
            "cohort_as_of_rule": (
                "prior_qualified_buys counts only rows with 0 < timestamp < entry_timestamp, "
                "so the cohort label is fixed before the measured window opens"
            ),
            "rejected_design": (
                "a symbol-level 'has a long-term profile' split was rejected as near-useless: "
                "94% of observations land in that cohort because the replay population is built "
                "from the same wallets that generate wallet_signal_profiles.json"
            ),
            "interpretation": "observational evidence, not realized exchange PnL",
        },
    }
    out = Path(out_path) if out_path is not None else None
    if out is not None:
        out.write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
    return result


if __name__ == "__main__":
    result = replay()
    print(json.dumps({k: result[k] for k in ("mode", "observation_count", "wallet_count", "statistics")}, ensure_ascii=False, indent=2))
